version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - ./downloads:/app/downloads
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis