services:
  - type: web
    name: pytube-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p downloads
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: N8N_UPLOAD_URL
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 